import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'
import { createSitemapXml, prerenderRoutes } from '../src/data/routeManifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')
const allRoutes = prerenderRoutes

/**
 * Strip ONLY the specific stale tags that react-helmet-async will replace.
 * Everything else (font preloads, favicons, manifest, critical CSS,
 * speculation rules, analytics) stays in the template.
 */
function stripStaleHeadTags(html) {
  // Remove any existing <title>...</title>
  html = html.replace(/<title[^>]*>[\s\S]*?<\/title>\s*/gi, '')
  // Remove only meta tags that react-helmet replaces (name/description, og:title, og:description)
  html = html.replace(/<meta\s+[^>]*name=["']description["'][^>]*>/gi, '')
  html = html.replace(/<meta\s+[^>]*property=["']og:title["'][^>]*>/gi, '')
  html = html.replace(/<meta\s+[^>]*property=["']og:description["'][^>]*>/gi, '')
  return html
}

async function run() {
  console.log('--- Starting Static Prerendering (SSG) ---')
  console.log(`Discovered ${allRoutes.length} total routes to render.`)

  // 1. Build the server-side bundle
  console.log('Building SSR bundle...')
  execSync('npx vite build --ssr src/entry-server.jsx --outDir dist-ssr', {
    cwd: rootDir,
    stdio: 'inherit'
  })

  // 2. Load the render function and template
  const templatePath = path.resolve(rootDir, 'dist/index.html')
  if (!fs.existsSync(templatePath)) {
    throw new Error('Client-side build index.html not found! Run npm run build first.')
  }
  let template = fs.readFileSync(templatePath, 'utf8')

  // Remove stale SEO tags baked into the client build so SSR tags win.
  template = stripStaleHeadTags(template)

  // Inject critical asset references (CSS + JS module) into <head>.
  // These are generated by Vite and not emitted by react-helmet, so they
  // must be added manually into the prerendered template.
  const cssFile = fs.readdirSync(path.join(rootDir, 'dist/assets')).find(f => f.endsWith('.css'))
  const jsFile = fs.readdirSync(path.join(rootDir, 'dist/assets')).find(f => f.startsWith('index-') && f.endsWith('.js'))
  const vendorFile = fs.readdirSync(path.join(rootDir, 'dist/assets')).find(f => f.startsWith('vendor-') && f.endsWith('.js'))
  if (cssFile) {
    template = template.replace('</head>', `    <link rel="stylesheet" crossorigin href="/assets/${cssFile}" />\n</head>`)
  }
  if (jsFile) {
    template = template.replace('</head>', `    <script type="module" crossorigin src="/assets/${jsFile}"></script>\n</head>`)
  }
  if (vendorFile) {
    template = template.replace('</head>', `    <link rel="modulepreload" crossorigin href="/assets/${vendorFile}" />\n</head>`)
  }

  const serverEntryPath = path.resolve(rootDir, 'dist-ssr/entry-server.js')
  const { render } = await import(`file://${serverEntryPath}`)

  // 3. Render each route
  for (const url of allRoutes) {
    console.log(`Prerendering route: ${url}`)
    const helmetContext = {}
    const { html } = render(url === '/404' ? '/404-not-found-route-trigger' : url, helmetContext)
    const { helmet } = helmetContext

    // Collect head tags
    let headTags = ''
    if (helmet) {
      headTags = [
        helmet.title?.toString(),
        helmet.meta?.toString(),
        helmet.link?.toString(),
        helmet.script?.toString()
      ].filter(Boolean).join('\n')
    }

    // Inject content into template
    let pageHtml = template
      .replace('<div id="root"></div>', `<div id="root">${html}</div>`)

    if (headTags) {
      pageHtml = pageHtml.replace('</head>', `${headTags}\n</head>`)
    }

    // Determine output file path
    let outputDir = path.resolve(rootDir, 'dist')
    let outputFileName = 'index.html'

    if (url === '/404') {
      outputFileName = '404.html'
    } else if (url !== '/') {
      const relativePath = url.replace(/^\//, '')
      outputDir = path.resolve(outputDir, relativePath)
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true })
      }
    }

    const outputPath = path.resolve(outputDir, outputFileName)
    fs.writeFileSync(outputPath, pageHtml, 'utf8')
  }

  // 4. Generate dynamic sitemap
  console.log('Generating dynamic sitemap.xml...')
  const sitemapXml = createSitemapXml(allRoutes)
  fs.writeFileSync(path.resolve(rootDir, 'dist/sitemap.xml'), sitemapXml, 'utf8')

  // 5. Clean up SSR build folder
  console.log('Cleaning up temporary SSR build directory...')
  fs.rmSync(path.resolve(rootDir, 'dist-ssr'), { recursive: true, force: true })

  console.log('--- Prerendering Complete! ---')
}

run().catch((err) => {
  console.error('Prerendering failed:', err)
  process.exit(1)
})